config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

   root 'welcome#index'

  post 'set_santa' => 'welcome#set_santa'
  resources :wishes, only: [:new, :create, :index]
  

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
   :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]


  belongs_to :santa, class_name: "User"
  has_one :child, class_name: "User", foreign_key: "santa_id"
  has_many :wishes

  validates :santa_id, uniqueness: true, allow_nil: true

  def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first#_or_create do |user|
#    user.email = auth.info.email
#    user.password = Devise.friendly_token[0,20]
#    user.name = auth.info.name   # assuming the user model has a name
#    user.remote_avatar_url =  auth.info.image
#  end
end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/models/wish.rb
class Wish < ActiveRecord::Base
  belongs_to :user
  validates :text, presence: true
  validates :user_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def configure_permitted_parameters
  devise_parameter_sanitizer.for(:sign_in) { |u| u.permit() }
end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @santa = current_user.santa
  end

  def set_santa
    current_user.santa = find_santa if current_user.santa == nil
    if current_user.save
      redirect_to root_path
    else
      redirect_to root_path, alert: "Something went wrong. Please try again."
    end
  end

  private
    def find_santa
      attr_users = User.where.not(santa_id: nil).pluck(:santa_id)
      attr_users << current_user.id
      avalaible_users =  User.all - User.find(attr_users)
      avalaible_users.sample
    end
end

app/controllers/wishes_controller.rb
class WishesController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @wishes = current_user.wishes
  end

  def new
    @wish = current_user.wishes.new
  end

  def create
    @wish = current_user.wishes.new(wish_params)
    if @wish.save
      redirect_to root_path, notice: "Wish added! Let's hope someone will make it happen."
    else
      render :new
    end
  end

  private
    def set_wish
      @wish = current_user.wishes.find(params[:id])
    end

    def wish_params
      params.require(:wish).permit(:text)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wishes_helper.rb
module WishesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Santa</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <span class="text-center"><%= bootstrap_flash %></span>
    <%= yield %>
  </div>

</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-sm-offset-3 col-md-offset-3">
      <h2 class="text-center">Welcome!</h2>
      <br>
      <% if current_user.sign_in_count == 1 %>
       <h3> Thank you, <%= current_user.name %>!</h3>
      <% end %>

      <% if Time.now < "2014-12-02" %>
        <h4>On the 5th of December, log in again to find out who is your Secret Santa.</h4>
        <h4>We will soon announce the date of gift-exchanging.</h4>
        <h4>Gifts should not be more expensive than 25 lei.</h4>
      <% end %>
        <h4><%= button_to "Dear Santa ...", new_wish_path, class: "btn btn-default btn-lg btn-block", method: :get %></h4>
        <h4><%= link_to "My wishlist", wishes_path, class: "btn btn-default btn-lg btn-block"  if current_user.wishes.any? %></h4>

      <% if @santa == nil and Time.now > "2014-12-02" %>
        <%= button_to "Apasăăă-l", set_santa_path, method: :post, data:{disable_with: 'Searching for your special person...' }, class: "btn btn-primary btn-lg btn-block" %>
      <% end %>

      <% if @santa %>
        <div class="well">
          <div class="text-center" style="padding: 25px;">
            <h4> Your special person is: </h4>
            <h3>
              <%= image_tag @santa.remote_avatar_url %>
              <%= link_to @santa.name, "https://facebook.com/#{current_user.uid}" %>
            </h3>
          </div>
          <%  if @santa.wishes.any? %>
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4>Dear Santa, </h4>
              </div>
              <div class="panel-body">
                <%= render @santa.wishes %>
              </div>
            </div>
          <% end %>
          </div>
          <% end %>

      <% if user_signed_in? %>
        <br><br><br>
        <p>
          Signed in as <%= current_user.name %>.
          <br>
           Not you? <%= link_to "Sign out", destroy_user_session_path,:method => :delete %>
           <br>
            <b>Disclamer: Once you've registered to Secret Santa, you may not unregister.
           <br>Your name will be added to the list and you will be remembered.
           <br>Please note that this is a serious thing and no kidding around is allowed. 
          </b>
        </p>
      <% end %>

    </div>
  </div>
</div>

app/views/wishes/_form.html.erb
 
<%= simple_form_for @wish, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">    
    <%= f.input :text, label: "Text", input_html: {:class =>  "form-control" }, label_html: { class:  "center-block"} %>
  </div>
  <div class="center-block form-group">
      <%= f.button :submit, :class => 'btn btn-primary' %>
      <%= link_to "Cancel", root_path, :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/wishes/_wish.html.erb
<p class="bg-info">&nbsp;&nbsp;<%= wish.text %></p>

app/views/wishes/index.html.erb
<div class="container" style="margin-top: 25px;">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-sm-offset-3 col-md-offset-3">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h2 class="text-center">My wishes</h2>
        </div>
        <div class="panel-body">
          <%= render @wishes %>
        </div>
      </div>
      <%= link_to "Back", root_path, :class => 'btn btn-default' %>
    </div>
  </div>
</div>

app/views/wishes/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 col-sm-offset-3 col-md-offset-3">
      <h2 class="text-center">Add a new wish</h2>
      <%= render :partial => 'form' %>
    </div>
  </div>
</div>